# -*- coding: utf-8 -*-
"""Conditional Statements and Loops_ANIS AQILAH.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-ToZhtxKvHJR0ZtBatEbjOynGq_qtQRA
"""

'''
Temperature Converter

Write a Python program to convert temperatures to and from Celsius and Fahrenheit.

[ Formula : c/5 = f-32/9 [ where c = temperature in celsius and f = temperature in fahrenheit ]

Expected Output :

60°C is 140 in Fahrenheit
45°F is 7 in Celsius
'''

#convert temperatures to and from Celsius and Fahrenheit
celsius = 60
fahrenheit = (celsius * 9/5) + 32
print(f"{celsius}°C is {fahrenheit:.0f} in Fahrenheit")

fahrenheit = 45
celsius = (fahrenheit - 32) * 5/9
print(f"{fahrenheit}°F is {celsius:.0f} in Celsius")

'''
Count Even and Odd Numbers

Write a Python program to count the number of even and odd numbers in a series of numbers

Sample numbers : numbers = (1, 2, 3, 4, 5, 6, 7, 8, 9)

Expected Output :

Number of even numbers : 5
Number of odd numbers : 4
'''
numbers = (1, 2, 3, 4, 5, 6, 7, 8, 9)

evenNumber = 0
oddNumber = 0

for num in numbers:
    if num % 2 == 0:
        evenNumber += 1
    else:
        oddNumber += 1

print("Number of even numbers :", evenNumber)
print("Number of odd numbers :", oddNumber)

'''
Fibonacci Series Between 0 and 50

Write a Python program to get the Fibonacci series between 0 and 50.

Note : The Fibonacci Sequence is the series of numbers :

0, 1, 1, 2, 3, 5, 8, 13, 21, ....
Every next number is found by adding up the two numbers before it.

Expected Output : 1 1 2 3 5 8 13 21 34
'''
a, b = 0, 1

while b < 50:   #(0,50)
    print(b, end=" ")
    a, b = b, a + b

'''
FizzBuzz Variation

Write a Python program that iterates the integers from 1 to 50. For multiples of three print "Fizz" instead of the number and for multiples of five print "Buzz". For numbers that are multiples of three and five, print "FizzBuzz".

Sample Output :

fizzbuzz
1
2
fizz
4
buzz
'''

for i in range(51):
    if i % 3 == 0 and i % 5 == 0:
        print("fizzbuzz")
    elif i % 3 == 0:
        print("fizz")
    elif i % 5 == 0:
        print("buzz")
    else:
        print(i)

'''
Password Validity Checker

Write a Python program to check the validity of passwords input by users.

Validation :

At least 1 letter between [a-z] and 1 letter between [A-Z].
At least 1 number between [0-9].
At least 1 character from [$#@].
Minimum length 6 characters.
Maximum length 16 characters.
'''
import re

p = input("Enter Your Password: ")

if len(p) < 6 or len(p) > 16:
    print("Invalid Password: length must be between 6 and 16 characters.")
elif not re.search("[a-z]", p):
    print("Invalid Password: must contain at least one lowercase letter.")
elif not re.search("[A-Z]", p):
    print("Invalid Password: must contain at least one uppercase letter.")
elif not re.search("[0-9]", p):
    print("Invalid Password: must contain at least one number.")
elif not re.search("[$#@]", p):
    print("Invalid Password: must contain at least one special character ($, #, or @).")
elif re.search(r"\s", p):
    print("Invalid Password: should not contain spaces.")
else:
    print("Valid Password ✅")

'''
Dog Age in Dog Years

Write a Python program to calculate a dog's age in dog years.

Note: For the first two years, a dog year is equal to 10.5 human years. After that, each dog year equals 4 human years.

Expected Output:

Input a dog's age in human years: 15
The dog's age in dog's years is 73
'''

humanYears = float(input("Input a dog's age in human years: "))

if humanYears <= 2:
    dogYears = humanYears * 10.5
else:
    dogYears = 2 * 10.5 + (humanYears - 2) * 4

print(f"The dog's age in dog's years is {dogYears:.0f}")

'''
Astrological Sign Finder

Write a Python program to display the astrological sign for a given date of birth.

Expected Output:

Input birthday: 15
Input month of birth (e.g. march, july etc): may
Your Astrological sign is : Taurus
'''

day = int(input("Input birthday: "))
month = input("Input month of birth (e.g. march, july etc): ").lower()

if month == 'december':
    sign = 'Sagittarius' if day < 22 else 'Capricorn'
if month == 'january':
    sign = 'Capricorn' if day < 20 else 'Aquarius'
if month == 'february':
    sign = 'Aquarius' if day < 19 else 'Pisces'
if month == 'march':
    sign = 'Pisces' if day < 21 else 'Aries'
if month == 'april':
    sign = 'Aries' if day < 20 else 'Taurus'
if month == 'may':
    sign = 'Taurus' if day < 21 else 'Gemini'
if month == 'june':
    sign = 'Gemini' if day < 21 else 'Cancer'
if month == 'july':
    sign = 'Cancer' if day < 23 else 'Leo'
if month == 'august':
    sign = 'Leo' if day < 23 else 'Virgo'
if month == 'september':
    sign = 'Virgo' if day < 23 else 'Libra'
if month == 'october':
    sign = 'Libra' if day < 23 else 'Scorpio'
if month == 'november':
    sign = 'Scorpio' if day < 22 else 'Sagittarius'

print("Your Astrological sign is :", sign)

'''
Chinese Zodiac Sign

Write a Python program to display the sign of the Chinese Zodiac for the given year in which you were born.

Expected Output:

Input your birth year: 1973
Your Zodiac sign : Ox
'''

year = int(input("Input your birth year: "))

zodiac = [
    "Monkey",
    "Rooster",
    "Dog",
    "Pig",
    "Rat",
    "Ox",
    "Tiger",
    "Rabbit",
    "Dragon",
    "Snake",
    "Horse",
    "Goat"
]

sign = zodiac[year % 12]

print("Your Zodiac sign :", sign)