# -*- coding: utf-8 -*-
"""DATA CLEANING__ANIS AQILAH.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cnC2F8QSKy8lHuNqTniE_8Jxy6bqf_4i
"""

import pandas as pd
import numpy as np

data=pd.read_csv('https://raw.githubusercontent.com/realpython/python-data-cleaning/refs/heads/master/Datasets/BL-Flickr-Images-Book.csv')
data.head()

data.drop(['Identifier'], axis=1, inplace=True)
data.info()

data['Publication_Year'] = data['Date of Publication'].astype(str).str.extract(r'(\d{4})')
data['Publication_Year'] = pd.to_numeric(data['Publication_Year'], errors='coerce')
data.head()

import numpy as np

data['Place of Publication'] = np.where(
    data['Place of Publication'].str.contains('London', na=False),
    'London',
    data['Place of Publication']
)
data['Place of Publication'] = np.where(
    data['Place of Publication'].str.contains('Oxford', na=False),
    'Oxford',
    data['Place of Publication']
)
data['Place of Publication'].head(10)

data = data.applymap(lambda x: x.strip() if isinstance(x, str) else x)
data.head()

data.rename(columns={
    'Edition Statement': 'Edition',
    'Date of Publication': 'Publication_Year'
}, inplace=True)
print(data.columns)

print(data.info())
print(data.isnull().sum())

data = data.dropna()

data.rename(columns={
    'Edition Statement': 'Edition',
    'Date of Publication': 'Publication_Year'
}, inplace=True)

# 7. Semak semula selepas ubah
print(data.info())
print(data.isnull().sum())