# -*- coding: utf-8 -*-
"""EXPLORATORY DATA ANALYSIS (EDA)_ANIS AQILAH.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PbUinAv2sfHCOFYYepi9o80oE6vuNqdN
"""

#EXPLORATORY DATA ANALYSIS (EDA)
#STEP 1
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
#to ignore warnings
import warnings
warnings.filterwarnings('ignore')

#STEP 2
data=pd.read_csv('https://raw.githubusercontent.com/realpython/python-data-cleaning/refs/heads/master/Datasets/BL-Flickr-Images-Book.csv')
data.head()

#STEP 3
data.drop(['Identifier'], axis=1, inplace=True)
data.info()

#STEP 4
data['Publication_Year'] = data['Date of Publication'].astype(str).str.extract(r'(\d{4})')
data['Publication_Year'] = pd.to_numeric(data['Publication_Year'], errors='coerce')
data.head()

#STEP 5
from datetime import date

current_year = date.today().year

data['Book_Age'] = current_year - data['Publication_Year'].astype(float)

data.head()

#STEP 6
# Check for duplicates
print("Number of duplicate rows:", data.duplicated().sum())

# Confirm data type conversion
print(data['Publication_Year'].dtypes)

# Check how many were converted to NaN
print("Missing years after conversion:", data['Publication_Year'].isnull().sum())

# View sample
print(data[['Date of Publication', 'Publication_Year']].head(10))

#STEP7
print(data.describe(include='all'))
print(data.nunique())

#STEP 8
print(data.describe())
print(data['Publisher'].value_counts().head(10))

#STEP 9
sns.histplot(data['Publication_Year'].dropna(), bins=30, kde=True)
plt.title('Distribution of Publication Year')
plt.show()

#STEP 10
from sklearn.preprocessing import MinMaxScaler

# Ensure numeric and fill missing
data['Book_Age'] = pd.to_numeric(data['Book_Age'], errors='coerce')
data['Book_Age'] = data['Book_Age'].fillna(0)

# Scale the feature
scaler = MinMaxScaler()
data['Book_Age_Scaled'] = scaler.fit_transform(data[['Book_Age']])

# Check result
print(data[['Book_Age', 'Book_Age_Scaled']].head())

#STEP 11
sns.boxplot(x='Publication_Year', data=data)
plt.title('Boxplot of Publication Year')
plt.show()

#STEP 12
plt.figure(figsize=(8,5))
sns.scatterplot(
    x='Publication_Year',
    y='Book_Age',
    data=data,
    alpha=0.6,
    color='teal'
)
plt.title('Publication Year vs Book Age')
plt.xlabel('Year of Publication')
plt.ylabel('Book Age')
plt.show()

#STEP 13
sns.pairplot(data[['Publication_Year', 'Book_Age']])
plt.show()

#STEP 14
# Check if missing values are gone
print(data[['Edition Statement', 'Publisher']].isnull().sum())

# Optional: view a few rows to confirm replacement
print(data[['Edition Statement', 'Publisher']].head(10))