# -*- coding: utf-8 -*-
"""Introduction _ANIS AQILAH.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UbW_Yr2g15acuHzsw1TnK9m3Gy1Z1k0o
"""

#String capitalize() Method
#Definition The capitalize() method returns a string where the first character is upper case, and the rest is lower case.
txt = "hello, my name is Anis and welcome to my Phyton world."

x = txt.capitalize()

print (x)

#String casefold() Method
#Definition The casefold() method returns a string where all the characters are lower case.

txt = "Hello,my name is Anis And Welcome To My Phyton World!"

x = txt.casefold()

print(x)

#String count() Method
#Definition The count() method returns the number of times a specified value appears in the string.
txt = "I love to eat banana,bananas are my favorite fruit"

x = txt.count("banana")

print(x)

#String endswith() Method
#Definition The endswith() method returns True if the string ends with the specified value, otherwise False.
txt = "Hello, welcome To My Phyton World."

x = txt.endswith(".")

print(x)

#String find() Method
#Definition The find() method finds the first occurrence of the specified value.
#The find() method returns -1 if the value is not found.


txt = "Hello, welcome to my world."

x = txt.find("welcome")

print(x)

#Python String islower() Method
#Definition The islower() method returns True if all the characters are in lower case, otherwise False.

txt = "hello phyton world!"

x = txt.islower()

print(x)

#String isupper() Method
#Definition The isupper() method returns True if all the characters are in upper case, otherwise False.Only aplhabet characters.

txt = "HELLO PHYTON WORLD!"

x = txt.isupper()

print(x)

#String lower() Method
#Definition The lower() method returns a string where all characters are lower case.

txt = "Hello my Phyton's FRIENDS"

x = txt.lower()

print(x)

#String upper() Method
#Definition The upper() method returns a string where all characters are in upper case.

txt = "Hello my Phyton's FRIENDS"

x = txt.upper()

print(x)

#String startswith() Method
#Definition The startswith() method returns True if the string starts with the specified value, otherwise False.

txt = "Hello, welcome to my world."

x = txt.startswith("Hello")

print(x)

#String swapcase() Method
#Definition The swapcase() method returns a string where all the upper case letters are lower case and vice versa.

txt = "hELLO MY NAME IS aNIS"

x = txt.swapcase()

print(x)

#String replace() Method
#Definition The replace() method replaces a specified phrase with another specified phrase.
txt = "I like pizzas"

x = txt.replace("pizzas", "apples")

print(x)