# -*- coding: utf-8 -*-
"""Assignment_KMEANS CLUSTERING _ANIS AQILAH.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tQHDscOGDxB8gqQnUp6dugECwAB6x3V9
"""

#KMEANS CLUSTERING
#a popular clustering algorithm that does a good job of grouping spherical data together into distinct groups.
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.datasets import make_blobs
import warnings
warnings.filterwarnings('ignore')

# Load housing data from GitHub
import pandas as pd

data = pd.read_csv(
    'https://raw.githubusercontent.com/onyx666dev/Datasets/refs/heads/main/housing.csv',
    usecols=['longitude', 'latitude', 'median_house_value']
)

# View first 5 rows
data.head()

# Visualize the data
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10,6))
sns.scatterplot(
    data=data,
    x='longitude',
    y='latitude',
    hue='median_house_value',
    palette='viridis',
    s=40,
    alpha=0.7
)

plt.title('Geographical Distribution of House Prices')
plt.xlabel('Longitude')
plt.ylabel('Latitude')
plt.legend(title='Median House Value', loc='upper right')
plt.show()

#Normalizing the data
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    data[['latitude', 'longitude']],          # independent variables
    data[['median_house_value']],             # dependent variable
    test_size=0.33,
    random_state=0)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

#Fitting and evaluating the model
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

kmeans = KMeans(n_clusters=3, random_state=0, n_init='auto')
kmeans.fit(X_train_scaled)

score = silhouette_score(X_train_scaled, kmeans.labels_)
print("Silhouette Score:", score)

sns.scatterplot(data = X_train, x = 'longitude', y = 'latitude', hue = kmeans.labels_)

sns.boxplot(x = kmeans.labels_, y = y_train['median_house_value'])

from sklearn.metrics import silhouette_score

silhouette_score(X_train_norm, kmeans.labels_, metric='euclidean')

#Choosing the best number of clusters'
K = range(2, 8)
fits = []
score = []


for k in K:
    # train the model for current value of k on training data
    model = KMeans(n_clusters = k, random_state = 0, n_init='auto').fit(X_train_norm)

    # append the model to fits
    fits.append(model)

    # Append the silhouette score to scores
    score.append(silhouette_score(X_train_norm, model.labels_, metric='euclidean'))

#look at =2
sns.scatterplot(data = X_train, x = 'longitude', y = 'latitude', hue = fits[0].labels_)

#look at =4
sns.scatterplot(data = X_train, x = 'longitude', y = 'latitude', hue = fits[2].labels_)

#look =7
sns.scatterplot(data = X_train, x = 'longitude', y = 'latitude', hue = fits[2].labels_)

sns.lineplot(x = K, y = score)

sns.scatterplot(data = X_train, x = 'longitude', y = 'latitude', hue = fits[3].labels_)

sns.boxplot(x = fits[3].labels_, y = y_train['median_house_value'])