# -*- coding: utf-8 -*-
"""RANDOM FOREST_ANIS AQILAH .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TAVrty_9DNjAXVXP96ZFrcEDCVGeacXe
"""

# Data Processing
import pandas as pd
import numpy as np

# Modelling
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, ConfusionMatrixDisplay
from sklearn.model_selection import RandomizedSearchCV, train_test_split
from scipy.stats import randint

# Tree Visualisation
from sklearn.tree import export_graphviz
from IPython.display import Image
import graphviz

from google.colab import files
upload = files.upload()

#load dataset
data=pd.read_csv('diabetes.csv')
print(data.shape)
data.head()

data.info()

data.isnull().sum()

data.dtypes

feature_cols = ['Pregnancies', 'Insulin', 'BMI', 'Age',
                'Glucose', 'BloodPressure', 'DiabetesPedigreeFunction']

X = data[feature_cols]
y = data['Outcome']

print(data.columns)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

rf = RandomForestClassifier()
rf.fit(X_train, y_train)

y_pred = rf.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Export the first three decision trees from the forest

for i in range(3):
    tree = rf.estimators_[i]
    dot_data = export_graphviz(tree,
                               feature_names=X_train.columns,
                               filled=True,
                               max_depth=2,
                               impurity=False,
                               proportion=True)
    graph = graphviz.Source(dot_data)
    display(graph)

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint


param_dist = {
    'n_estimators': randint(100, 500),
    'max_depth': randint(3, 15),
    'min_samples_split': randint(2, 10),
    'min_samples_leaf': randint(1, 5)
}


rf = RandomForestClassifier(random_state=42, n_jobs=-1)


rand_search = RandomizedSearchCV(
    estimator=rf,
    param_distributions=param_dist,
    n_iter=10,             # bilangan kombinasi rawak nak diuji
    cv=5,                  # 5-fold cross validation
    scoring='accuracy',
    n_jobs=-1,             # guna semua core CPU
    random_state=42
)

rand_search.fit(X_train, y_train)


print("Best Parameters:", rand_search.best_params_)
print("Best Accuracy (CV):", rand_search.best_score_)

# Create a variable for the best model
best_rf = rand_search.best_estimator_

# Print the best hyperparameters
print('Best hyperparameters:',  rand_search.best_params_)

# Generate predictions with the best model
y_pred = best_rf.predict(X_test)

# Create the confusion matrix
cm = confusion_matrix(y_test, y_pred)

ConfusionMatrixDisplay(confusion_matrix=cm).plot();

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score


knn = KNeighborsClassifier(n_neighbors=5)  # boleh ubah nilai k, contohnya 3, 7, 9

knn.fit(X_train, y_train)


y_pred = knn.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

# Create a series containing feature importances from the model and feature names from the training data
importances = pd.Series(best_rf.feature_importances_, index=X_train.columns)
importances.sort_values(ascending=False).plot.bar()